version: '2.1'
services:
    mysql:
        container_name: mysql
        image: mysql:5.7.26
        ports:
            - "3306:3306"
        volumes:
            - mysqldata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=yudafu2019
            - MYSQL_DATABASE=test
    nginx:
        container_name: nginx
        image: nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./nginx/web:/usr/share/nginx/html
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/log:/var/log/nginx
    reids:
        container_name: redis
        image: redis
        command: redis-server --requirepass yudafu2019
        ports:
            - "6379:6379"
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
        command: mongod --auth
        volumes:
            - mongodata:/data/db
    gcc:
        container_name: gcc
        image: gcc
        build: ./gcc
        volumes:
            - ./gcc/work:/home/work
        command: /home/start
    node:
        container_name: node
        image: node
        build: ./node
        volumes:
            - ./node/work:/home/work
        ports:
            - "8000:8000"
        command: node /home/start.js
    go:
        container_name: go
        image: golang
        build: ./go
        volumes:
            - ./go/work:/home/work
        ports:
            - "9000:9000"
        command: /home/start
volumes:
    mongodata:
    mysqldata:
